name: CodeLegacy

on:
  workflow_dispatch:
  
jobs:

  build:
  
    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
  
    - name: Restore Packages
      run: nuget restore CodeLegacy\Flowframes.sln

    - name: Build solution
      run: msbuild CodeLegacy\Flowframes.sln -t:rebuild -property:Configuration=Release -property:Platform=x64

    - name: Upload log files
      uses: actions/upload-artifact@v4
      with:
        name: Flowframes-CodeLegacy
        path: .\CodeLegacy\bin\RelGui\
